# Generated by Django 4.2.14 on 2024-08-16 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/', verbose_name='image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('rate', models.FloatField(default=0, verbose_name='rate')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('date', models.DateField(verbose_name='date')),
                ('avg_rate', models.FloatField(default=0, verbose_name='rate')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meal.food')),
            ],
            options={
                'verbose_name': 'meal',
                'verbose_name_plural': 'meals',
                'db_table': 'meal',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('rate', models.IntegerField(default=5, verbose_name='rate')),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meal.meal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rate',
                'verbose_name_plural': 'rates',
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('text', models.TextField(verbose_name='text')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
            },
        ),
    ]
