# Generated by Django 4.2.14 on 2024-08-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='rate',
            new_name='avg_rate',
        ),
    ]
