# Generated by Django 4.2.14 on 2024-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrunner',
            name='input_mapping',
            field=models.JSONField(default=''),
        ),
    ]
