# Generated by Django 4.2.14 on 2024-09-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_workflowrunner_input_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrunner',
            name='input_mapping',
            field=models.JSONField(default=dict),
        ),
    ]
