# Generated by Django 4.2.14 on 2024-07-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='meal',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
