# Generated by Django 4.2.14 on 2024-07-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_feedback_rating_meal_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Comment',
        ),
    ]
